import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  leftGun: {
    position: "relative",
    width: "70%",
    top: "12%",
    right: "10%",
    resizeMode: "contain",
  },
  rightGun: {
    position: "relative",
    width: "70%",
    bottom: "200%",
    left: "40%",
    resizeMode: "contain",
  },

  menuContainer: {
    position: "absolute",
    flex: 1,
    flexDirection: "column",
  },
  signPostTitle: {
    backgroundColor: "#eaeaea",
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#c7522a",
    width: "70%",
    textAlign: "center",
    fontSize: 36,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 30,
  },
  upperSignTextBox: {
    width: "100%",
    height: "75%",
    bottom: "15%",
    right: "15%",
    resizeMode: "contain",
  },
  lowerSignContainer: {
    width: "120%",
    height: "120%",
    right: "0%",
    top: "0%",

    resizeMode: "contain",
  },
  signPostTextBox: {
    alignItems: "center",
    justifyContent: "center",
    bottom: "59%",
    left: "0%",
  },

  buttonContainer: {
    margin: "2%",
    right: 0,
    bottom: 0,
    display: "flex",
    alignItems: "flex-end",
  },
  buttonActive: {
    borderRadius: 20,
    borderWidth: 4,
    borderColor: "#ffffff",
    paddingVertical: 14,
    paddingHorizontal: 10,
    backgroundColor: "#878787",
    width: "25%",
  },
  buttonActiveText: {
    backgroundColor: "#bfbfbf",
    maxHeight: 80,
    color: "black",
    padding: 2,
    borderRadius: 6,
    fontWeight: "bold",
    textTransform: "uppercase",
    fontSize: 16,
    textAlign: "center",
  },
  buttonInactive: {
    borderRadius: 20,
    borderWidth: 4,
    borderColor: "#878787",
    paddingVertical: 14,
    paddingHorizontal: 10,
    backgroundColor: "#bfbfbf",
    width: "25%",
  },
  buttonInactiveText: {
    backgroundColor: "#878787",
    maxHeight: 80,
    color: "white",
    padding: 2,
    borderRadius: 6,
    fontWeight: "bold",
    textTransform: "uppercase",
    fontSize: 16,
    textAlign: "center",
  },
  textLargeOverlay: {
    position: "absolute",
    top: "65%",
    left: 0,
    right: 0,
    bottom: 0,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 36,
    zIndex: 2,
  },
  textSmallOverlay: {
    position: "absolute",
    top: "65%",
    left: 0,
    right: 0,
    bottom: 0,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 16,
    zIndex: 2,
  },
});
